name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Clean install dependencies
        run: npm ci

      - name: Deploy
        run: |
          git config user.name "Sajal N. Shrestha" && git config user.email "sajal.shres@gmail.com"
          npm run deploy
